# Generated by Django 2.2 on 2019-05-02 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salas', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='aceita',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='avaliada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='avaliada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='comentario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_hora_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_hora_reserva',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='laboratorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='laboratorios.Laboratorio'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='sala',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='salas.Sala'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='justificativa',
            field=models.TextField(),
        ),
    ]
