# Generated by Django 2.2 on 2019-05-02 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_auto_20190502_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='laboratorios.Laboratorio'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='salas.Sala'),
        ),
    ]
