# Generated by Django 2.2 on 2019-04-29 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('capacidade', models.PositiveIntegerField()),
                ('ocupado', models.BooleanField()),
                ('responsaveis', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
