# Generated by Django 2.2 on 2019-04-29 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratorios', '0003_laboratorio_responsaveis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratorio',
            old_name='ocupado',
            new_name='reservado',
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='reservado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='responsaveis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
