# Generated by Django 2.2 on 2019-04-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0004_auto_20190429_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratorio',
            old_name='responsaveis',
            new_name='responsavel',
        ),
    ]
