# Generated by Django 2.2 on 2019-04-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0005_auto_20190429_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='reservado',
            field=models.BooleanField(default=False),
        ),
    ]
