# Generated by Django 2.2 on 2019-05-28 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0001_initial'),
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapas.Mapa'),
        ),
        migrations.AddField(
            model_name='sala',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
