# Generated by Django 2.2.1 on 2019-05-20 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0001_initial'),
        ('salas', '0002_auto_20190520_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapas.Mapa'),
        ),
    ]
