# Generated by Django 2.2 on 2019-05-24 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('registro', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('imagem_perfil', models.ImageField(blank=True, null=True, upload_to='perfil')),
                ('aprovado', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('Aluno', 'Aluno'), ('Coordenador', 'Coordenador')], max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
