# Generated by Django 2.2 on 2019-05-26 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20190524_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='imagem_perfil',
        ),
    ]
